import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// Read package.json synchronously so the version is available at config-load
// time. Avoids JSON-import attribute incompatibilities across Node versions.
const pkg = JSON.parse(
  readFileSync(resolve(__dirname, 'package.json'), 'utf8'),
) as { version: string };

/**
 * Replaces `__BUILD_HASH__` in the emitted `dist/sw.js` with a per-build
 * stamp (`<package version>-<build timestamp in base36>`). This forces the
 * service worker's `CACHE_NAME` to change every release, so the
 * `activate` handler evicts the previous cache and clients pick up the
 * new bundle on next navigation.
 */
function injectPwaCacheVersion(): Plugin {
  const stamp = `${pkg.version}-${Date.now().toString(36)}`;
  return {
    name: 'inject-pwa-cache-version',
    apply: 'build',
    closeBundle() {
      const swPath = resolve(__dirname, 'dist/sw.js');
      if (!existsSync(swPath)) return;
      const content = readFileSync(swPath, 'utf8');
      writeFileSync(swPath, content.replace(/__BUILD_HASH__/g, stamp));
    },
  };
}

export default defineConfig({
  plugins: [react(), injectPwaCacheVersion()],
  base: './',
  // Inject the package version as a build-time constant so user-visible
  // surfaces (About dialog, etc.) stay in lockstep with package.json.
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  esbuild: {
    drop: ['console', 'debugger'],  // Remove console.* and debugger in production
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.includes('node_modules')) {
            if (
              id.includes('@codemirror') ||
              id.includes('@uiw/react-codemirror') ||
              id.includes('codemirror')
            ) {
              return 'codemirror';
            }
            if (id.includes('react-dom') || id.includes('/react/')) {
              return 'react';
            }
          }
          // Split heavy schema data into its own chunk so the main bundle
          // is smaller, parses faster, and the schema can be cached
          // independently across releases.
          if (id.includes('src/schema/teiP5Generated')) {
            return 'tei-p5';
          }
          if (id.includes('src/schema/teiAutoGenerated')) {
            return 'tei-auto';
          }
          return undefined;
        },
      },
    },
  },
});
