import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { injectCsp } from './vite-csp';
import { buildPrecacheList, applySwBuildData } from './vite-sw';

// Read package.json synchronously so the version is available at config-load
// time. Avoids JSON-import attribute incompatibilities across Node versions.
const pkg = JSON.parse(
  readFileSync(resolve(__dirname, 'package.json'), 'utf8'),
) as { version: string };

/**
 * Post-processes the emitted `dist/sw.js`:
 *   - `__BUILD_HASH__` → a per-build stamp (`<version>-<base36 timestamp>`),
 *     so the service worker's `CACHE_NAME` changes every release and the
 *     `activate` handler evicts the previous cache.
 *   - the precache marker → the list of hashed JS/CSS chunks emitted this
 *     build, so the full app shell is precached at install and the first
 *     offline start works (audit #9). The marker-missing case throws.
 * Pure logic lives in ./vite-sw.ts (unit-tested); this hook does the IO.
 */
function injectServiceWorkerBuildData(): Plugin {
  const stamp = `${pkg.version}-${Date.now().toString(36)}`;
  return {
    name: 'inject-sw-build-data',
    apply: 'build',
    closeBundle() {
      const swPath = resolve(__dirname, 'dist/sw.js');
      if (!existsSync(swPath)) return;
      const assetsDir = resolve(__dirname, 'dist/assets');
      const assetFiles = existsSync(assetsDir) ? readdirSync(assetsDir) : [];
      const precache = buildPrecacheList(assetFiles);
      const out = applySwBuildData(readFileSync(swPath, 'utf8'), { stamp, precache });
      writeFileSync(swPath, out);
    },
  };
}

// The CSP plugin (`injectCsp`) lives in ./vite-csp.ts so its injection logic
// can be unit-tested (tests/injectCsp.test.ts) — it now fails the build if the
// index.html anchor is missing instead of silently shipping no CSP (audit #2).

export default defineConfig({
  plugins: [react(), injectServiceWorkerBuildData(), injectCsp()],
  base: './',
  // Inject the package version as a build-time constant so user-visible
  // surfaces (About dialog, etc.) stay in lockstep with package.json.
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  esbuild: {
    drop: ['console', 'debugger'],  // Remove console.* and debugger in production
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.includes('node_modules')) {
            if (
              id.includes('@codemirror') ||
              id.includes('@uiw/react-codemirror') ||
              id.includes('codemirror')
            ) {
              return 'codemirror';
            }
            if (id.includes('react-dom') || id.includes('/react/')) {
              return 'react';
            }
          }
          // Split heavy schema data into its own chunk so the main bundle
          // is smaller, parses faster, and the schema can be cached
          // independently across releases.
          if (id.includes('src/schema/teiP5Generated')) {
            return 'tei-p5';
          }
          if (id.includes('src/schema/teiAutoGenerated')) {
            return 'tei-auto';
          }
          return undefined;
        },
      },
    },
  },
});
